name: style

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Style: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: rustfmt
        run: rustup component add rustfmt

      - name: style
        run: cargo fmt --all --check

      - name: clippy
        run: cargo clippy
